### ISSUE TITLE
"Found new Queue, imported into database" does not show in dashboard...

### ISSUE THREAD

**Issue by rgransier** [campai-bv/autotask-dashboards-os#18]
Looks like the import works well; the cronjob.log file shows any newly discovered Queues, Status, Resources etc. but they do not show up in the webportal.
Do I have to reset some cache, and what do I loose with that?

thanks already,

Roger
version 1.3.2

**Comment by jarrodmast** [comment]
when you say it doesn't show up - do you mean it doesn't get added to the widgets in your display automatically, or are you referring to the dash config not having it as a selectable option?

**Comment by rgransier** [comment]
it does not show up in the config; normally there would be something like: not defined yet... but I don't see any added queues

**Comment by rgransier** [comment]
I now have a new error in the debug.log (and the same in cronjob.log):
2013-09-13 09:45:15 Notice: Undefined property: stdClass::$StartDateTime in [/var/www/app/Plugin/Autotask/Console/Command/Task/CalculateTotalsForTimeEntriesTask.php, line 85]

keeps repeating every 5 minutes.

**Comment by coencoppens** [comment]
@rgransier this issue gets solved in the 1.4.0 release.

If you want to quick fix you can copy the appropriate lines:
https://github.com/coencoppens/autotask-dashboards/blob/1.4.0/Console/Command/Task/CalculateTotalsForTimeEntriesTask.php#L71
or of course give the 1.4.0 branch a test run :-)

**Comment by jarrodmast** [comment]
That's a bug in 1.3.X pretty sure it was fixed in the 1.4 branch. 
Try pull the 1.40 code?

**Comment by coencoppens** [comment]
Great minds think alike ;-)
