### ISSUE TITLE
IP access restriction problem

### ISSUE THREAD

**Issue by efiniste** [campai-bv/autotask-dashboards-os#21]
Hi Guys,

Just upgraded from 1.2.0 to 1.3.2 and I'm now presented with the Access Restriction page when I try to open the dashboard. Whenever I try to add an IP address I get an error ".htaccess is not writeable".

Have I missed something?

thanks,

Steve

**Comment by efiniste** [comment]
With further research, this seems to be only affecting the settings page, the dashboards themselves are working fine but whenever I click on the settings menu I'm given the Access Restriction page and am unable to add any IPs.

**Comment by coencoppens** [comment]
Hi Steve,

You'll have to give the .htaccess file the correct permissions for this feature to work, probably 777. I'll update the appropriate installation files :-)

Btw: there's an update available which will prevent issues with creating dashboards, [v1.3.3](https://github.com/coencoppens/autotask-dashboards/releases/tag/v1.3.3)
