### ISSUE TITLE
CakePHP translates tinyint(1) mysql field into boolean

### ISSUE THREAD

**Issue by coencoppens** [campai-bv/autotask-dashboards-os#22]
Which breaks the ticketsource widget :(

Solution: modify your database field to tinyint(2). This needs to be applied to table "Tickets", field "ticketsource_id". For more info, see https://cakephp.lighthouseapp.com/projects/42648/tickets/4065-cakephp-24-mysql-55-tinyint1-boolean

**Comment by MattParr** [comment]
```
Source
    In Person/Onsite = 6
    Whitelabel = 11
    Phone = 2
    Other = 1
    Monitoring Alert = 8
    Insourced = -2
    Client Portal = -1
    Email = 4
```
