### ISSUE TITLE
How to copy the complete configuration and database to a new server?

### ISSUE THREAD

**Issue by rgransier** [campai-bv/autotask-dashboards-os#24]
Hi Coen,

I have a live server, presenting version 1.3.2. but there seem to be some issues with it; probably due to some upgrades and changes.
I also run a test server which does not have any issues and already running 1.4.0-RC1.

How can I copy all content and configuration from the test into the live server?

regards,
Roger

**Comment by jarrodmast** [comment]
hey this should be as simple as backing up the database and restoring on the live server. As for the app itself - whether you copy your autotask plugin from the test to live server or if you prefer to simply grab the latest from the repo is up to you.. 

Providing you already have a working system with CakePHP installed and working I would think that should be all you need..

**Comment by rgransier** [comment]
thanks for the tip; what is the best way to backup the database? I would appreciate a little help, for example: is there phpmyadmin installed by default?, what is the name/location of the database? Are there any (webbased tools) to backup/restore..?
Thanks again for your help.

**Comment by jarrodmast** [comment]
No problems, I'd have to leave that part to Coen, I'm assuming you are
running the virtual machine from Coen?
I would expect phpmyadmin to be installed on the vm otherwise I'm not much
help there!

**Comment by coencoppens** [comment]
The VM has only a webserver and MySQL running, nothing fancy like phpmyadmin has been installed.

I use Navicat, but you can also use something like (SqlYog)[https://www.webyog.com/], to connect to my database. From there I can do everything you can do with phpmyadmin. It's really up to you; some people just do everything from the command line.

The database details can be found in the database configuration file

```
/var/www/app/Config/database.php
```

I think the default is:
User: autotask
Password: autotask

And you connect to localhost.

Hope this is helpful.
