### ISSUE TITLE
Board reset

### ISSUE THREAD

**Issue by techworksinc** [campai-bv/autotask-dashboards-os#26]
The dashboards  all reset to zero at 3pm PT. Is there a way to change this?

**Comment by coencoppens** [comment]
@techworksinc there is no specific "hard reset", the data is fetched every 5 minutes. Even though the next version will have an improvement sync routine, you shouldn't be getting an empty dashboard.

Standard debug questions:
- What version are you running?
- What does your cronjob.log file look like?

**Comment by jarrodmast** [comment]
Is this time zone related?
What version are you running?
Sounds similar to the bug fixed with the time zone patch in 1.4...?

**Comment by techworksinc** [comment]
How can I upgrade to 1.4? I didn't see a download link. I set it up using the west coast.

-------- Original message --------

**Comment by coencoppens** [comment]
@techworksinc it's documented in the [readme](https://github.com/coencoppens/autotask-dashboards/blob/master/README.md#upgrading) :)

**Comment by techworksinc** [comment]
Thanks for the response. How do I import the file into the VM for upgrade?

**Comment by coencoppens** [comment]
Even though it's an older post I think it'll be useful for your situation: [How to upgrade your VM](http://www.autotask.campai.nl/documentation/how-to-upgrade-your-vm/)

**Comment by techworksinc** [comment]
I followed the steps to wget the latest version, but got error 1054 unkown exception at line 7, show-sla.

Any idea where to go from here?

**Comment by techworksinc** [comment]
Is there a way to do a clean install with the 1.4.0 RC-1? Thanks

Casey

**Comment by coencoppens** [comment]
There is ;-) When releasing the 1.4.0 I'll make sure to update the docs so you can start fresh.
