### ISSUE TITLE
Rearranging widgets not always working

### ISSUE THREAD

**Issue by ghost** [campai-bv/autotask-dashboards-os#30]
Rearranging the widgets does not always work. The moved widgets resets on saving to the old position. Did this in Safari and Firefox, after 5 minutes (automatic reloading of the data) the widget is on the right position.

**Comment by coencoppens** [comment]
@SjoerdSlabbers ,
- What version are you using?
- What is your cronjob.log saying (maybe boost the log level in the bootstrap a bit)?
- Is it happening in a specific browser?

**Comment by heints** [comment]
Hei Guys,

Our install is suffering from same issue (took the VMWARE and update-id it to 1.4RC) but I think it may be related to some cache-ing issue... As When widgets are arranged and save is pressed the widgets pop back to the place before save, but after some minutes they will go to the their desired places :)

Maybe to add some cache / cookie policy + reload & refresh together with the "Save" button. That would probably solve this glitch.

br,
Hendrik

**Comment by jarrodmast** [comment]
Got to admit I've been noticing the same issue and getting positions to save can be even more challenging when you are moving things around that the row/col counts can get confused

**Comment by coencoppens** [comment]
My suggestion would be caching too. Checking into this :-)

I've added a small patch that fixed the issue, at least at my dev. environment: 5ba6ae05226d61b393f506c11050a2ff6cec4509

**Comment by jarrodmast** [comment]
I've tested this tweak and can confirm I can now easily update my dash widgets and moving/rearranging is flawless so far!

**Comment by coencoppens** [comment]
Sweet :)
