### ISSUE TITLE
BUG - Tickets By Source Widget only shows data for current day

### ISSUE THREAD

**Issue by PaulSells** [campai-bv/autotask-dashboards-os#31]
Tickets by source widget only shows data for current day. The previous 6 days are on the chart but the data is missing

**Comment by MindGas** [comment]
Hi,

Widget needs run for a week to show full 7 day history. From your description it sounds that it has been running for more than one day. What cronjob says? Did it completed import of open tickets everyday? Did tickets by source calculation finished successfully? I use PHPmyAdmin to check if data exist in DB

**Comment by coencoppens** [comment]
The weird thing is, the data gets collected for the current day, but on the next day everything gets reset to 0. My gut feeling tells me it's another one of those pesky timezone issues (timezone in this case is Europe/London).

**Comment by coencoppens** [comment]
@MindaugasMeskauskas @PaulSells Since there wasn't any progress I've taken the liberty of trying to fix it myself (see commit above). Giving it a testrun now. Keep you posted :-)

**Comment by coencoppens** [comment]
Sweet, the fixes seem to have solved the problem :-) @PaulSells your Dashboard contains 2 days of data now.
