### ISSUE TITLE
Problem and Incident Tickets missing from stats

### ISSUE THREAD

**Issue by jarrodmast** [campai-bv/autotask-dashboards-os#32]
Hey Coen, I just noticed, I think, that we aren't getting any stats through on tickets that are of type Problem or Incident - I checked the tickets table and couldn't find any matching my ticket numbers that were listed as incidents or problems... its making my metrics look a little lower than they should be :P

**Comment by coencoppens** [comment]
@jarrodmast , are those specific ticket statuses? It sounds strange because I don't think there's any filter on fetching open tickets.

**Comment by jarrodmast** [comment]
Hi Coen - they aren't specific statuses - that's a type of ticket. I'm wondering if the API has made some adjustments to handle problem/incident tickets as this was a recent improvement for Autotask..?

**Comment by coencoppens** [comment]
So if I understand you correctly, changing the field "Ticket Type" makes the tickets go missing?

![image](https://f.cloud.github.com/assets/2962964/1741058/6762d9fc-63da-11e3-848d-b6ba7b9d8809.png)

**Comment by jarrodmast** [comment]
Exactly! Try it

**Comment by coencoppens** [comment]
@jarrodmast I've given it a try by creating a ticket and moving it along all of my available types (Incident, Problem and Service Request). It keeps getting imported when the cronjob runs.

To make it easier to debug, you can run your cronjob by using the -d option:

```
Autotask.import_from_autotask -d open_tickets
```

That way only the open tickets are fetched.

**Comment by jarrodmast** [comment]
I believe this was related to my previous issue with regards to time entries missing - the user account that was in use for the dash was not a full API admin - since correcting this I believe we have had 100% of ticket data.
