### ISSUE TITLE
Top 10 Tickets

### ISSUE THREAD

**Issue by rsantiago-srs** [campai-bv/autotask-dashboards-os#37]
How can I modify this so I show top 5 tickets instead of top 10?  Also, any way to isolate the tickets and show top 5 in a certain status?

Using 1.3.2.

Thanks.

**Comment by jarrodmast** [comment]
in Dashboard.php just after you see the following

```
                        // 10 latest tickets.
                        case 9:
```

there is a 'limit' parameter where you can adjust the number of tickets returned.
also immediately after that line you could add the 'conditions' array to select specific ticket statuses - see the example below for limiting it to 5 tickets currently in the "new" status

```
                        // 10 latest tickets.
                        case 9:

                            App::uses( 'Ticket', 'Autotask.Model' );
                            $this->Ticket = new Ticket();

                            $aWidget = array_merge( $aWidget, array(
                                    'Widgetdata' => $this->Ticket->find( 'all', array(
                                            'limit' => 5
                                        ,   'conditions' => array(
                                                'Ticket.ticketstatus_id =' => 2
                                            )
                                        ,   'order' => 'created DESC'
                                    ) )
                            ) );

                        break;
```

I haven't tested this code but it should get your desired result

**Comment by coencoppens** [comment]
That should do the trick :)

**Comment by glennda37** [comment]
I'm Not sure if I am being dumb here but i cannot find the required setting?

I am using the virtual appliance.

**Comment by coencoppens** [comment]
@glennda37 here are 2 links to the specific lines:
- [Line 386](https://github.com/coencoppens/autotask-dashboards/blob/1.5.1/Model/Dashboard.php#L386)
- [Line 398](https://github.com/coencoppens/autotask-dashboards/blob/1.5.1/Model/Dashboard.php#L398)

Does that help?

**Comment by glennda37** [comment]
I found it now - i had downloaded the appliance and not updated it and therefore I appeared to have no Dashboard.php file. updated and found. Thanks!
