### ISSUE TITLE
Resources Ordered by Total Time Worked

### ISSUE THREAD

**Issue by rsantiago-srs** [campai-bv/autotask-dashboards-os#38]
Running v1.4.0; The resources widget is now ordering by total time worked as opposed to the original total tickets completed.

How can I get this changed back?

**Comment by jarrodmast** [comment]
Around line 176 of Model/Resource.php
update the line to read as follows

``` php
            $aResourceTotals['Resource'] = Hash::sort( $aResourceTotals['Resource'], '{n}.closed', 'desc', 'numeric' );
```

hope that helps!
