### ISSUE TITLE
Is there a way to change what status the the kill rate and closed today check  

### ISSUE THREAD

**Issue by cybercon22** [campai-bv/autotask-dashboards-os#39]
I was wondering if there was a way to change the completed in the kill rate and closed today in resources to check a different status for these.

**Comment by jarrodmast** [comment]
To change the kill_rate - in Model/Ticket.php line 218 find

``` php
            $aConditions['completed'] = array(
                    'Ticket.completed >=' => date( 'Y-m-d' )
            );
```

and change to read

``` php
            $aConditions['completed'] = array(
                    'Ticket.ticketstatus_id =' => 7
            );
```

change status id to the value of the status you want to count as "completed" the example above is "Waiting Customer" on my system.
I haven't tested this code but it should be what you're after... let me know!

As for the Closed Today count - you can simply choose a different ticket status widget for display and then adjust the widget title as required.
