### ISSUE TITLE
After Upgrading from 1.2 to 1.3.2 errors logged in cronjob.log

### ISSUE THREAD

**Issue by jarrodmast** [campai-bv/autotask-dashboards-os#4]
**Problem:**
Receive the following in the cron log, however the import appears to work fine.

```
2013-08-16 12:30:52 Cronjob:  ..could not delete view cache!                                                                               
2013-08-16 12:30:52 Cronjob: Failed: we've encountered some errors while running the import script. 
```

**Solution:**
Delete old bootstrap.php and alter a new copy of bootstrap.default.php in /app/Plugin/Autotask/Config

**Explanation:**
New code was added to control cache, as a result extra configuration options are available and required in the bootstrap

**Suggestion:**
Set default values at runtime in case bootstrap does not define these values. Update documentation to refer to these settings in the upgrade notes

**Comment by coencoppens** [comment]
The error probably occurs because of a missing Cache configuration in the bootstrap.

Even though I've added it to the README file it seems you missed it, which indicates this isn't the correct place for these kind of notifications. With the updated documentation you probably mean giving a heads up on the release notes (website/GitHub)?

I like your suggestion about setting the default, sounds like the proper way to take care of it. I'll try and figure out how to add this in a decent way :-)

**Comment by jarrodmast** [comment]
I was looking at the upgrade instructions in the read me file, didn't see
it mentioned?

Yes a default would be better for catching that error anyways ;-)

**Comment by coencoppens** [comment]
Sorry, I meant the CHANGELOG file :) Next time I'll publish the steps required to the website, changelog and optional the readme.

Anyway, did the addition of the cache configuration solve the problem? Or was it a matter of (manually) deleting the cache files?

**Comment by jarrodmast** [comment]
Ah yes, adding the cache config items to bootstrap allowed it to delete cache as normal. That error was masking the fact that the actual problem was that the variables for cache were unset altogether.

**Comment by coencoppens** [comment]
For anyone having this issue, the lines required to add to your /app/Plugin/Autotask/Config/bootstrap.php file are:

``` php
/**
 * Enables the models to use caching.
 */
Cache::config( '1_hour', array(
        'engine' => 'File'
    ,   'duration' => '+1 hours'
    ,   'path' => CACHE
    ,   'prefix' => 'cake_1_hour_'
));
```
