### ISSUE TITLE
"Access Denied" is Console

### ISSUE THREAD

**Issue by tbeerapu** [campai-bv/autotask-dashboards-os#42]
Setup the cronjob that imports your Autotask data: sh </path/to/your/cake/installation/>/lib/CakeConsole/cake -app /path/to/your/application/folder/app Autotask.import_from_autotask

This command returns the access denied error

**Comment by coencoppens** [comment]
You're not supposed to use the "/path/to/your/application/folder" for real; adjust it so you get a path that actually points to your app :-)

**Comment by tbeerapu** [comment]
Oh yeah, I used the path to my installation folder. The issue was with the AT credentials. It's fixed now. Thanks
