### ISSUE TITLE
Cron job not grabbing Resource names

### ISSUE THREAD

**Issue by tbeerapu** [campai-bv/autotask-dashboards-os#43]
Cron job not grabbing Resource names

**Comment by coencoppens** [comment]
@tbeerapu thanks for reporting. I ran into this myself this morning while setting up a new Dashboard too.

It appears the devs at Autotask have been so kind to update the current API and change the way certain results are returned. The code doesn't expect this format, so it breaks.

You can expect a fix from me asap.

**Comment by tbeerapu** [comment]
Thanks!

**Comment by coencoppens** [comment]
I've released version 1.5.0 which fixes the issue.

Note that there is 1 important change to the cronjob: it has gotten a flag (-f). If you run the cronjob like you always did it will only take into account the data of today. If you want to check tickets that have been created before today for example, get resources, queues and the whole shebang, you need to run the cronjob with -f.

Care to give it a test run?

**Comment by tbeerapu** [comment]
Ran it, It did get the names of the resources but not all the resources are downloaded, Only few

**Comment by coencoppens** [comment]
@tbeerapu , there's another issue that I think is related. Please see this comment: https://github.com/coencoppens/autotask-dashboards/issues/46#issuecomment-34866748

**Comment by coencoppens** [comment]
@tbeerapu , can you update to 1.5.2 and give the new import a try? You're now able to get all active resources by using the data_to_check flag:

```
-d resources
```
