### ISSUE TITLE
Change Clock Format  

### ISSUE THREAD

**Issue by cybercon22** [campai-bv/autotask-dashboards-os#45]
Is there a way to change the clock from 24 hours to 12 hours ?

**Comment by coencoppens** [comment]
Edit line 5 in

```
/View/Elements/Widgets/clock.ctp
```

Change

```
date( 'H:i' )
```

into

```
date('h:i')
```

There's a lot more that you can do with the time formatting there if you'd like :) You can find all available time options on the [PHP website](http://nl1.php.net/manual/en/function.date.php).

**Comment by jarrodmast** [comment]
Hey Coen, just a thought, should put that (date formatter options) into the
dash settings, even if it's just a text field to supply your own date
string, I know I've customised it on our dash as I'm sure others would too

**Comment by coencoppens** [comment]
@jarrodmast @cybercon22 what do you think about this commit: 5a8ee14 ?

I've added these options for time:

``` javascript
{
'H:i':'14:25',
'G:i':'7:25',
'h:i':'02:25',
'h:i a':'02:25 pm',
'h:i A':'02:25 PM'
}
```

and these for dates:

``` javascript
{
'l, d F':'tuesday, 18 february',
'd F':'18 february',
'F jS': 'February 18rd',
'j F Y': '18 February 2014',
'j F y': '18 February 14'
}
```

Are these lists of options sufficient or am I missing some? Maybe you added others?
