### ISSUE TITLE
Kill Rate widget "Completed" Label

### ISSUE THREAD

**Issue by jarrodmast** [campai-bv/autotask-dashboards-os#5]
Whilst Kill Rate - completed - is at Zero, the Term 'Completed' (or whatever has been configured from the reorganise screen) doesn't appear in the widget, pretty sure once this value moves on from zero it works as expected..

**Comment by coencoppens** [comment]
You're up to 1.3.2 right?

My (personalized) widget appears like this:
![image](https://f.cloud.github.com/assets/2962964/973882/627649e2-0642-11e3-9705-5d3692962d28.png)

**Comment by jarrodmast** [comment]
yes 1.3.2 still - works fine when the 2pm point rolls passed and numbers fill up

![image](https://f.cloud.github.com/assets/5233149/999369/905d3720-0a2b-11e3-9b2d-d350bf27a80d.png)

**Comment by coencoppens** [comment]
With the "2pm point" you probably mean the issue described in issue #2 .

Even if I delete the entry of the current day from the database (so it doesn't have any data to begin with) the widgets appears with both completed and new get set to 0, taking the full width, so I can't seem to reproduce this.

**Comment by jarrodmast** [comment]
Data is zeroed now for "Completed" tickets. Regarding 2pm - the timezone bug in issue #2 - I have 0 completed until 2pm, once that number is greater than 0 - this kill rate display works properly... strange right?

![image](https://f.cloud.github.com/assets/5233149/999712/639feabe-0a37-11e3-8b49-42765900aaf0.png)

I can login and tweak the number back up from 0 and it works properly - should i double check my code against the source?

**Comment by jarrodmast** [comment]
OK I've worked this out Coen - It is because of the automatic calculation of the width %.
I edited killrate.ctp and commented out the code that set the width of the completed bar, and put a manual number of 20%

![image](https://f.cloud.github.com/assets/5233149/999953/7d8700c8-0a3e-11e3-8cd8-e861da3f5e2e.png)

This only becomes a problem when the ratio from new to completed is really high (0 completed versus 20 new).

See source code from the generated webpage associated with the screenshot above.

```
<table class="table kill-rate">
    <thead>
        <tr>
            <th colspan="2" style="text-align: center;"><h4 style="margin-top: 20px;" class="jeditable" id="display_name">Kill Rate Graph</h4></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="width: 100%;">
                <div class="progress" style="height: 50px; width: 100%;">
                    <div class="bar bar-danger" style="width: 100%;">
                        <h3>15 <span class="jeditable_setting" id="title_new">FreshPoo</span></h3>
                    </div>
                </div>
            </td>

                                <td rowspan="2">
                    <h1>87%</h1>
                </td>

        </tr>
        <tr>
            <td>
                <div class="progress" style="height: 50px; width: 20%;">
                    <div class="bar bar-success" style="width: 100%;">
                        <h3>13 <span class="jeditable_setting" id="title_completed">Done and DustedCheese</span></h3>
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>
```

So I can finally reproduce this output on demand!

A good suggestion might be to add an extra column for the label and only have the number in the dynamically sized bar ?

**Comment by jarrodmast** [comment]
Hi Coen,

this new code looks much better and works perfectly - i've already pulled it from git and tested :)

I have another suggestion - i've tweaked the getKillRate function in ticket.php

from Model/Ticket.php lines 252-264

``` php
              if( 0 == $iTicketsCompletedToday ) {
                $iTicketsCompletedToday = 1;
            }

            if( 0 == $iTicketsCreatedToday ) {
                $iTicketsCreatedToday = 1;
            }

            if( $iTicketsCreatedToday > $iTicketsCompletedToday ) {
                $aKillRate['killed_progress_width_%'] = $iFullWidth * ( ( ( 100*$iTicketsCompletedToday ) / $iTicketsCreatedToday ) / 100 );
            } else {
                $aKillRate['new_progress_width_%'] = $iFullWidth * ( ( ( 100*$iTicketsCreatedToday ) / $iTicketsCompletedToday ) / 100 );
            }
```

replace with:

``` php
            if(( $iTicketsCompletedToday > 0 ) && ( $iTicketsCreatedToday > 0 )) {
                // if there is a sensible ratio (BOTH are greater than zero)
                if( ($iTicketsCreatedToday > $iTicketsCompletedToday)) {
                    $aKillRate['killed_progress_width_%'] = $iFullWidth * ( ( ( 100*$iTicketsCompletedToday ) / $iTicketsCreatedToday ) / 100 );
                } else {
                    $aKillRate['new_progress_width_%'] = $iFullWidth * ( ( ( 100*$iTicketsCreatedToday ) / $iTicketsCompletedToday ) / 100 );
                }
                // otherwise if one of the values are zero set it to 100/0 for the bar width
                } elseif (( 0 == $iTicketsCompletedToday ) && ( $iTicketsCreatedToday > 0 )) {
                    $aKillRate['killed_progress_width_%'] = 0;
                } elseif (( $iTicketsCompletedToday > 0 ) && ( $iTicketsCreatedToday == 0 )) {
                    $aKillRate['new_progress_width_%'] = 0;
            } 
            //failing that, leave both set to $iFullWidth as both counts should be zero
```

should still avoid the divbyzero and also shows the bar as empty when one value zeroed, or both full when both at zero - its a suggested code, you might have a smarter way of doing the same ..? :D

**Comment by coencoppens** [comment]
Good idea to pimp the widget while we're at it :-) I've changed not only the width calculation but also the percentage displaying.

One thing I'd like to discuss is whether it's logical to display percentages above 100% and negatives percentages. 

Say you have 0 new tickets and 5 completed. Does it make sense that your kill rate is 500%?

Or you have 10 new tickets, and only completed 5. Is your kill rate -50%?

**Comment by jarrodmast** [comment]
I think its best if the ratio is a comparison of Closed to New. 
In your example i would think 0 New and 5 completed should Be simply 100%, then when it moves on to 1 New and 6 completed, start to work out the percentages...

if you had 10 new and 5 complete, the number should be simply 50%
if you had 10 new and 20 complete it should be 200%
it might be a cool addition to use the history on that figure too to show the movement as we do with the ticket status counters (up/down x%)

this is my opinion, others may differ...
