### ISSUE TITLE
SOAP-Error Parsing WSDL

### ISSUE THREAD

**Issue by Scottdawes** [campai-bv/autotask-dashboards-os#54]
Hi there I have updated to the latest version 1.5 and have only been using the product for a few weeks however I am repeatably getting a SOAP-Error aftert the webserver has been running for 24 hours or so.

The initial import works succesfully and it works for the first day,  I then come in and recieve this message.

"Fatal Error Error:  SOAP-ERROR:  Parsing WSDL: Couldn't load from 'https://webservices4.autotask.net/atservices/1.5/atws/wsd1' : failed load external entity "https://webservices4.autotask.net/atservices/1.5/atws.wsd1" in [/var/www/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php, line 271]

Error:  SOAP-ERROR: Parsing WSDL:  Couldn't load from 'https://webservices4.autotask.net/atservices/1.5/atws/wsd1' : failed to load external entity "https://webservices4.autotask.net/atservices/1.5/atws.wsd1" in [/var/www/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php,  line 271]

As a side not I am running the virtual machine that you have provided and I have then manually updated to 1.5 using the instructions for upgrading to 1.2 on your website but by modifing where required the specific file names to go to 1.5.

I also used the dashboards-for-autotask.sql file to re-create the database as there is no autotask 1.4.0-to-1.5.0.sql in the downloaded files.

Thanks

**Comment by coencoppens** [comment]
Hi @Scottdawes,

Thanks for describing your issue this way! Seems like your API URL is slightly off.

Try this:

```
https://webservices4.autotask.net/atservices/1.5/atws.wsdl
```

Note the last character is a letter L, not the number one. You could also copy/paste the URL from the bootstrap.php comments to prevent this from going wrong.

Does that solve your issue?

**Comment by Scottdawes** [comment]
apologies it is an L,  I am running the VM through a VSphere window which isn't allowing me to copy.

**Comment by coencoppens** [comment]
They never come that easy do they ^_^

The problem seems to come from something other than the code (now we know the URL is ok) because it's SOAP that's crashing.

A few questions that come to mind are:
- Can you reach the API at all from your VM?
- Maybe you're missing something on your VM like cURL, did you install that?
- What's the command that you can execute without problems?

Since the error is SOAP related I'd say you shouldn't be able to run any import at all.

**Comment by Scottdawes** [comment]
Can you reach the API at all from your VM?  - The initial few hours works fine.  I installed the VM yesterday and it worked until I left work at 6PM GMT,  then arrving this morning with no changes there is this messsage.

Maybe you're missing something on your VM like cURL, did you install that? - I have only taken the Virtual machine that you have provided and upgraded this as per the upgrade isntructions to get this to 1.5

What's the command that you can execute without problems? - The command I am trying to execute is - su - www-data -c "sh /var/www/lib/Cake/Console/cake -app /var/www/app Autotask.import_from_autotask >> /var/www/app/tmp/logs/cronjob.log" . This command worked yesterday but is now failing.

**Comment by coencoppens** [comment]
Can you access the API at all? Try something like

```
w3m https://webservices4.autotask.net/atservices/1.5/atws.wsdl
```

and see if you get a proper response?

**Comment by Scottdawes** [comment]
I receive a Segmentation fault (core dumped)

Scott Dawes
Service Delivery Manager

[cid:image001.gif@01CF2CA6.A49F72A0]http://www.solsoft.co.uk/
Tel:

0845 073 0930

www.solsoft.co.ukhttp://www.solsoft.co.uk

Direct:

www.solsoftdevelopment.co.ukhttp://www.solsoftdevelopment.co.uk

**Comment by Scottdawes** [comment]
FYI I have just re-installed the VM again and updated this and recorded the steps that I have taken.

I will let you know if this stops working again tomorrow and will then be able to show you the steps I took to upgrade etc.

Thanks

**Comment by Scottdawes** [comment]
After a fresh install the error has appeared again I have confirmed that this seems to be an issue with the way in which I have manually set the IP address.

I am using the command Sudo vi /etc/network/interfaces  is this the correct process?

**Comment by coencoppens** [comment]
@Scottdawes great effort in getting this solved! If I understand correctly you want to update your network configuration. In that case you're using the right command (at least on ubuntu). A quick search led me to [this page](http://www.howtogeek.com/howto/ubuntu/change-ubuntu-server-from-dhcp-to-a-static-ip-address/).

How did you figure out your network settings are giving the problems?

**Comment by Scottdawes** [comment]
I found this out the hard way by re-installing through a step by step guide and seeing where the process failed.

Unfotunately I did not think this was a networking issue as I could access the web page from another machine but unfortunately it seems that when I statically set the IP the server is no longer able to talk to the outside world.  I may try to reserver the IP address instead but didn't really want to on a virtual machine.

Many Thanks

**Comment by Scottdawes** [comment]
I do now have an issue where the Queue names have not all re-populated,  about 60% of the queue names have been filled out but some that have previosuly been found in other installs are not recognised.

Is there a way to refresh the whole database,  I'm not worried about the information currently that has been pulled out.

Thanks

**Comment by coencoppens** [comment]
Sure :) Just empty the queues table in your case:

```
mysql -uroot -p -e "TRUNCATE autotask.queues"
```

But does this mean the original problem is solved?

**Comment by Scottdawes** [comment]
Yes the other problem seems to be configuration issues based on the static IP.

Thanks for all your help.

Scott Dawes
Service Delivery Manager

[cid:image001.gif@01CF2D64.82F75320]http://www.solsoft.co.uk/
Tel:

0845 073 0930

www.solsoft.co.ukhttp://www.solsoft.co.uk

Direct:

www.solsoftdevelopment.co.ukhttp://www.solsoftdevelopment.co.uk
