### ISSUE TITLE
Number of tickets is incorrect in the Queues Widget

### ISSUE THREAD

**Issue by Scottdawes** [campai-bv/autotask-dashboards-os#56]
Good Afternoon, I have an issue where there is an incorrect amount of information being shown in the Queues widget.  

It is currently showing more tickets than there are.

I have ran this command to try and clear out its information and to then download the current but after the download it is still present.

I have confirmed the amount of tickets by using the tickets search in autotask.

Command used:  

mysql -uroot -pdash autotask -e "TRUNCATE autotask.queues".

This cleared out the widget but now the information is incorrect.

**Comment by Scottdawes** [comment]
Is there any update as to my above issue?

**Comment by coencoppens** [comment]
@Scottdawes , sorry, I'd swear I replied to this! Obviously GitHub replies don't lie.. So here I go again:

What do you mean with "showing more tickets than there are?" Do you mean that, for example, you're seeing 10 tickets on the Dashboard for a certain queue, but there only 5 tickets in that queue in Autotask?

Clearing the queues table doesn't do anything for the totals, it's only used to store their names. You can try truncating it's related tables but I don't think that will solve the actual problem.

Can you take a look in the tickets table to see which tickets you have for a certain queue compared to the ones Autotask is showing?

**Comment by Scottdawes** [comment]
Hi yes basically we have a queue which is currently kept clear so the idea is that there are never any tickets in that queue.

There are currently no tickets in the queue yet the dashboards show 32 Tickets in the queue, these appear still in the database yet they have been moved.

**Comment by Scottdawes** [comment]
This is the same across all of the queues that I have they are showing more tickets than are actually in the queues.

**Comment by coencoppens** [comment]
Sounds like your running the cronjob only with the "-f" flag, which results in your tables not being truncated. Is that the case?

**Comment by Scottdawes** [comment]
My cronjob is  

*/15 \* \* \* \* su - www-data -c "sh /var/www/lib/Cake/Console/cake -app /var/www/app Autotask.import_from_autotask >> /var/www/app/tmp/logs/cronjob.log"

**Comment by coencoppens** [comment]
That's the problem :) I've made a change to the cronjobs which should have led to a new major version to prevent these issues.

Please see the part of the readme about the cronjobs here: https://github.com/coencoppens/autotask-dashboards/blob/master/README.md#installation

Does that solve your issue?

**Comment by Scottdawes** [comment]
Thanks that seems to have solved the issues,  I will confirm tomorrow that my cronjob for tonight is working but you can close this for now as I think it will now be resolved.

Thanks for you help
