### ISSUE TITLE
resources showing on the top  by the time they spent rather than the number of tickets

### ISSUE THREAD

**Issue by awach** [campai-bv/autotask-dashboards-os#60]
Hi all,

This is my first post. 
After installing dashboard we noticed that the resources are showing by the time spent on the tickets rather than tickets closed. 
so the resource with the highest score no1 is the one who worked longest time and not the one who closed the most tickets. 

how do we change so the cup goes to the one who close the most tickets?

thanks everyone in advance

**Comment by coencoppens** [comment]
Hi @awach , please see #38 on how to solve this :-)

**Comment by awach** [comment]
Brilliant . Thank you very much. All is working perfectly fine now :)
