### ISSUE TITLE
Open Ticket Percentages

### ISSUE THREAD

**Issue by spleggenkuhle** [campai-bv/autotask-dashboards-os#79]
The total Ticket open per ticket status shows correctly for the numbers. However the percentages all show 0% with the blue arrow pointing to the right. The only one that shows a percentage is the "Open" status and it sits at 8.8% still with a blue arrow to the side. I feel that these are not being calculated correctly. Any ideas?

**Comment by coencoppens** [comment]
Known issue, please see [this comment](https://github.com/coencoppens/autotask-dashboards/issues/73#issuecomment-42924583).

**Comment by spleggenkuhle** [comment]
I have already seen that comment. However, I have data for over a week, and the cronjobs run without any errors.

**Comment by coencoppens** [comment]
Me referencing that issue was meant to move the conversation to that issue ;) So please let us continue there.
