### ISSUE TITLE
Changing Chart colors

### ISSUE THREAD

**Issue by jfinegagne** [campai-bv/autotask-dashboards-os#88]
Hi,

I'm looking at the widgets and trying to find where they call colors for the bars (mostly in kill rate and new vs. closed). The red green is great, but to have company colors would be fun. Is there a way to do this?

Thanks!
Jesse

**Comment by coencoppens** [comment]
It depends on the widget that you want to change. If its the kill rate widget, that's bootstrap colors. The other charts/graphs are based on HighCharts, they have their own configurations at
- https://github.com/campai-bv/autotask-dashboards-os/blob/master/webroot/js/killRate.js
- https://github.com/campai-bv/autotask-dashboards-os/blob/master/webroot/js/queueHealth.js
- https://github.com/campai-bv/autotask-dashboards-os/blob/master/webroot/js/ticketSource.js

etc

**Comment by jfinegagne** [comment]
Thanks!

---

Jesse Fine-Gagne I.T. Team Lead
JIG Technologies
Simplifying Technology for Business

T: 416-850-2684 x122           TF: 1-866-615-2786
E: jesse@jig.tomailto:jesse.fine-gagne@jig.to        E-Support: helpdesk@jig.tomailto:helpdesk@jig.to
http://www.jigtechnologies.comhttp://www.jigtechnologies.com/
[cid:8BDFDAA4-E430-4B30-8D8D-7822BB768437]http://twitter.com/JIGTechnologies
Our goal is to respond within 1 hour,
 for escalation please email sla@jig.tomailto:sla@jig.to
