### ISSUE TITLE
Advice on creating our own widgets

### ISSUE THREAD

**Issue by mattrbailey** [campai-bv/autotask-dashboards-os#89]
We want to create our own widgets for the dash board. Some of them will be similar to the "show kill count". 

We can see the ctp files and they should be ok to modify, but wanted to add our own custom widgets that can be selected under the resources section.

Is there any documentation on how this can be archived? Any help files etc?

Thanks,

**Comment by coencoppens** [comment]
Hi @mattrbailey , unfortunately there isn't any documentation available on this, so it's a matter of reverse engineering. If it's a widget that you think everyone can benefit from, it might be worth adding it as a feature request.
